package com.example.mybookshopapp.data.model.author;

import com.example.mybookshopapp.data.model.book.BookEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * @author karl
 */

@Entity
@Table(name="author")
@ApiModel(description = "data model of author entity")
@Getter
@Setter
public class AuthorEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 3)
    private Integer Id;
    @Column(columnDefinition = "VARCHAR(255)")
    private String photo;
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String slug;
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "name of author", example = "Mark Twen", position = 1)
    private String name;
    @Column(columnDefinition = "TEXT")
    private String description;

    @ManyToMany
    @JoinTable(name = "book2author", joinColumns = @JoinColumn(name = "author_id"), inverseJoinColumns = @JoinColumn(name = "book_id"))
    @JsonIgnore
    private List<BookEntity> books = new ArrayList<>();


    public AuthorEntity(ArrayList<String> authors) {
        if (authors != null) {
            this.name = authors.toString();
        }

    }
    public AuthorEntity() {}

    @Override
    public String toString() {
        return name;
    }
}
